### ISSUE TITLE
Clarify adding the subscribe box to the IHR 2018 website 

### ISSUE THREAD

**Issue by kaodro** [mozilla/internet-health-report#46]
Hi @cadecairos and @santostiago cc/@dhakelila 

We need to add the subscribe box to the website as depicted in the design prototype (https://projects.invisionapp.com/share/9XEIUP73P#/screens/265255492) in two spots: at the bottom of the page and in the Participate section at the top.  The box needs to comply with the legal requirements. We can replicate the structure of the box from https://internethealthreport.org/ where the deciding factors are 

a) there needs to be a consent box " I’m okay with mozilla handling my info as explained in this privacy notice." where and the consent box needs to be ticked before the user is able to sign up (the sign up fails if the box is not ticked)
b)depending on the language of the page the sign up generates subscription to one of the four languages

Not sure if there is some ready to go code to be added to wordpress for that? Just wanted to start this thread and connect you two, so it gets done. Thanks!

**Comment by santostiago** [comment]
@kaodro what would you like to happen when they subscribe? Do you have a place to manage the subscriptions (like mailchimp or similar)? Should they be added to a list?

**Comment by kaodro** [comment]
@santostiago Mozilla has an Email team that manages also our IHR subscriptions through their database (they use salesforce and we have a "bucket" in their subscribers database). There should be a piece of code you can use for that and simply add it to the website. It is the same as on internethealthreport.org so you can have a look how it is solved there. Then you can change the CSS to match the design. Otherwise I am sure @cadecairos can help you, Solana mentioned he helped with that the last time. Thanks!

**Comment by santostiago** [comment]
Hi @kaodro! Thanks for the reply.
I can't see the setup of the subscription box in internethealthreport.org, so I'd need the help of @cadecairos to know how to integrate it.

**Comment by santostiago** [comment]
Hi @kaodro @cadecairos. Any news on this subject?

**Comment by cadecairos** [comment]
@santostiago On the bottom of the internethealthreport.org page, in the footer, is the subscription form. I've pulled out the HTML and stripped the classes to share it here:

```html
<form id="newsletter_form" name="newsletter_form" action="https://www.mozilla.org/en-US/newsletter/" method="post">
    <input id="fmt" name="fmt" value="H" type="hidden">
    <input id="lang" name="lang" value="en" type="hidden">
    <input id="newsletters" name="newsletters" value="internet-health-report-group" type="hidden">
    <div>
        <label for="email" class="hidden-label">Email: </label>
        <input id="email" name="email" required="required" placeholder="Email address" size="30" type="email">
        <div>
            <label for="privacy">
                <input id="privacy" name="privacy" required="" type="checkbox">
                <div>I’m okay with mozilla handling my info as explained in this <a href="https://www.mozilla.org/privacy/websites/">privacy notice</a>.</div>
            </label>
        </div>
        <button id="newsletter_submit" type="submit" >Sign up</button>
    </div>
</form>
```

@kaodro I'm presuming the newsletter name is still the same as last time?

**Comment by cadecairos** [comment]
Just want to note that the newsletter's hidden `lang` input should reflect the language of the page being viewed.
